language: rust
sudo: false
cache: cargo

rust:
  - stable

services:
  - docker

before_install:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      ./tests/run-all-tests $KAFKA_VER &&
      travis-cargo bench &&
      travis-cargo --only stable doc

env:
  global:
    - RUST_TEST_THREADS: 1

  matrix:
    # 0.8 doesn't support secure settings
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=NONE SECURES=
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=SNAPPY SECURES=
    - KAFKA_VER=0.8.2.2 COMPRESSIONS=GZIP SECURES=

    - KAFKA_VER=0.9.0.1 COMPRESSIONS=NONE SECURES=
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=NONE SECURES=secure
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=SNAPPY SECURES=
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=SNAPPY SECURES=secure
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=GZIP SECURES=
    - KAFKA_VER=0.9.0.1 COMPRESSIONS=GZIP SECURES=secure

    - KAFKA_VER=0.10.2.1 COMPRESSIONS=NONE SECURES=
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=NONE SECURES=secure
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=SNAPPY SECURES=
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=SNAPPY SECURES=secure
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=GZIP SECURES=
    - KAFKA_VER=0.10.2.1 COMPRESSIONS=GZIP SECURES=secure

    - KAFKA_VER=0.11.0.1 COMPRESSIONS=NONE SECURES=
    - KAFKA_VER=0.11.0.1 COMPRESSIONS=NONE SECURES=secure
    - KAFKA_VER=0.11.0.1 COMPRESSIONS=SNAPPY SECURES=
    - KAFKA_VER=0.11.0.1 COMPRESSIONS=SNAPPY SECURES=secure
    - KAFKA_VER=0.11.0.1 COMPRESSIONS=GZIP SECURES=
    - KAFKA_VER=0.11.0.1 COMPRESSIONS=GZIP SECURES=secure

    - KAFKA_VER=1.0.0 COMPRESSIONS=NONE SECURES=
    - KAFKA_VER=1.0.0 COMPRESSIONS=NONE SECURES=secure
    - KAFKA_VER=1.0.0 COMPRESSIONS=SNAPPY SECURES=
    - KAFKA_VER=1.0.0 COMPRESSIONS=SNAPPY SECURES=secure
    - KAFKA_VER=1.0.0 COMPRESSIONS=GZIP SECURES=
    - KAFKA_VER=1.0.0 COMPRESSIONS=GZIP SECURES=secure
