[package]
name = "awc"
version = "1.0.1"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Actix http client."
readme = "README.md"
keywords = ["actix", "http", "framework", "async", "web"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/awc/"
categories = ["network-programming", "asynchronous",
              "web-programming::http-client",
              "web-programming::websocket"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "awc"
path = "src/lib.rs"

[package.metadata.docs.rs]
features = ["openssl", "rustls", "compress"]

[features]
default = ["compress"]

# openssl
openssl = ["open-ssl", "actix-http/openssl"]

# rustls
rustls = ["rust-tls", "actix-http/rustls"]

# content-encoding support
compress = ["actix-http/compress"]

[dependencies]
actix-codec = "0.2.0"
actix-service = "1.0.0"
actix-http = "1.0.0"
actix-rt = "1.0.0"

base64 = "0.11"
bytes = "0.5.3"
derive_more = "0.99.2"
futures-core = "0.3.1"
log =" 0.4"
mime = "0.3"
percent-encoding = "2.1"
rand = "0.7"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6.1"
open-ssl = { version="0.10", package="openssl", optional = true }
rust-tls = { version = "0.16.0", package="rustls", optional = true, features = ["dangerous_configuration"]  }

[dev-dependencies]
actix-connect = { version = "1.0.1", features=["openssl"] }
actix-web = { version = "2.0.0-alpha.5", features=["openssl"] }
actix-http = { version = "1.0.0", features=["openssl"] }
actix-http-test = { version = "1.0.0", features=["openssl"] }
actix-utils = "1.0.3"
actix-server = "1.0.0"
actix-tls = { version = "1.0.0", features=["openssl", "rustls"] }
brotli = "3.3.0"
flate2 = "1.0.13"
futures = "0.3.1"
env_logger = "0.6"
webpki = "0.21"
