[package]
name = "actix-files"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "Static files support for actix web."
readme = "README.md"
keywords = ["actix", "http", "async", "futures"]
homepage = "https://actix.rs"
repository = "https://github.com/actix/actix-web.git"
documentation = "https://docs.rs/actix-files/"
categories = ["asynchronous", "web-programming::http-server"]
license = "MIT/Apache-2.0"
edition = "2018"
workspace = ".."

[lib]
name = "actix_files"
path = "src/lib.rs"

[dependencies]
actix-web = { version = "2.0.0-alpha.6", default-features = false }
actix-http = "1.0.0"
actix-service = "1.0.0"
bitflags = "1"
bytes = "0.5.3"
futures = "0.3.1"
derive_more = "0.99.2"
log = "0.4"
mime = "0.3"
mime_guess = "2.0.1"
percent-encoding = "2.1"
v_htmlescape = "0.4"

[dev-dependencies]
actix-rt = "1.0.0"
actix-web = { version = "2.0.0-alpha.6", features=["openssl"] }
