language: rust

matrix:
    include:
    # Linux 64bit
    - os: linux
        rust: stable
        compiler: gcc
    - os: linux
        rust: nightly
        compiler: gcc

    # macOS 64bit
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
        os: osx
        rust: stable
        osx_image: xcode9.4
        compiler: clang
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
        os: osx
        rust: nightly
        osx_image: xcode9.4
        compiler: clang

    # Windows 64bit
    - os: windows
        rust: stable

cache:
  directories:
   - $HOME/.cargo
before-cache:
  - rm -rf $HOME/.cargo/registry
sudo: false
script:
    - cargo build
    - cargo test
    - cargo bench
