[package]
name = "kafka_demo"
version = "0.1.0"
authors = ["lianwei <lianwei1994@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = {path = "./rust-kafka"}